<a href="https://colab.research.google.com/github/merttezcan/ML-Homeworks/blob/main/svm_digits.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.svm import SVC

digits = datasets.load_digits()
from sklearn.model_selection import train_test_split
X = digits.data
y = digits.target
X_train,X_test, y_train, y_test=train_test_split(X,y,test_size=0.30)
C = 1
gammas = [0.1, 1, 10, 100]

In [ ]:
linear_svc = SVC(kernel='linear', C=C)
linear_svc.fit(X_train, y_train)

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
pred=linear_svc.predict(X_test)

In [ ]:
for gamma in gammas:
  rbf_svc = SVC(kernel='rbf', gamma = gamma, C=C)
  rbf_svc.fit(X_train, y_train)
  pred=rbf_svc.predict(X_test)
  
  print(confusion_matrix(y_test,pred))
  print(classification_report(y_test, pred))
  print("with gamma", gamma)
  print("----------------------------------")

[[ 0  0  0  0  0  0 50  0  0  0]
 [ 0  1  0  0  0  0 50  0  0  0]
 [ 0  0  0  0  0  0 52  0  0  0]
 [ 0  0  0  0  0  0 61  0  0  0]
 [ 0  0  0  0  0  0 59  0  0  0]
 [ 0  0  0  0  0  0 56  0  0  0]
 [ 0  0  0  0  0  0 50  0  0  0]
 [ 0  0  0  0  0  0 56  0  0  0]
 [ 0  0  0  0  0  0 53  0  0  0]
 [ 0  0  0  0  0  0 52  0  0  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        50
           1       1.00      0.02      0.04        51
           2       0.00      0.00      0.00        52
           3       0.00      0.00      0.00        61
           4       0.00      0.00      0.00        59
           5       0.00      0.00      0.00        56
           6       0.09      1.00      0.17        50
           7       0.00      0.00      0.00        56
           8       0.00      0.00      0.00        53
           9       0.00      0.00      0.00        52

    accuracy                           0.09       540
   macro avg       

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[ 0  0  0  0  0  0 50  0  0  0]
 [ 0  0  0  0  0  0 51  0  0  0]
 [ 0  0  0  0  0  0 52  0  0  0]
 [ 0  0  0  0  0  0 61  0  0  0]
 [ 0  0  0  0  0  0 59  0  0  0]
 [ 0  0  0  0  0  0 56  0  0  0]
 [ 0  0  0  0  0  0 50  0  0  0]
 [ 0  0  0  0  0  0 56  0  0  0]
 [ 0  0  0  0  0  0 53  0  0  0]
 [ 0  0  0  0  0  0 52  0  0  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        50
           1       0.00      0.00      0.00        51
           2       0.00      0.00      0.00        52
           3       0.00      0.00      0.00        61
           4       0.00      0.00      0.00        59
           5       0.00      0.00      0.00        56
           6       0.09      1.00      0.17        50
           7       0.00      0.00      0.00        56
           8       0.00      0.00      0.00        53
           9       0.00      0.00      0.00        52

    accuracy                           0.09       540
   macro avg       

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[ 0  0  0  0  0  0 50  0  0  0]
 [ 0  2  0  0  0  0 49  0  0  0]
 [ 0  0  0  0  0  0 52  0  0  0]
 [ 0  0  0  0  0  0 61  0  0  0]
 [ 0  0  0  0  0  0 59  0  0  0]
 [ 0  0  0  0  0  0 56  0  0  0]
 [ 0  0  0  0  0  0 50  0  0  0]
 [ 0  0  0  0  0  0 56  0  0  0]
 [ 0  0  0  0  0  0 53  0  0  0]
 [ 0  0  0  0  0  0 52  0  0  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        50
           1       1.00      0.04      0.08        51
           2       0.00      0.00      0.00        52
           3       0.00      0.00      0.00        61
           4       0.00      0.00      0.00        59
           5       0.00      0.00      0.00        56
           6       0.09      1.00      0.17        50
           7       0.00      0.00      0.00        56
           8       0.00      0.00      0.00        53
           9       0.00      0.00      0.00        52

    accuracy                           0.10       540
   macro avg       

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[ 0  0  0  0  0  0 50  0  0  0]
 [ 0  0  0  0  0  0 51  0  0  0]
 [ 0  0  0  0  0  0 52  0  0  0]
 [ 0  0  0  0  0  0 61  0  0  0]
 [ 0  0  0  0  0  0 59  0  0  0]
 [ 0  0  0  0  0  0 56  0  0  0]
 [ 0  0  0  0  0  0 50  0  0  0]
 [ 0  0  0  0  0  0 56  0  0  0]
 [ 0  0  0  0  0  0 53  0  0  0]
 [ 0  0  0  0  0  0 52  0  0  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        50
           1       0.00      0.00      0.00        51
           2       0.00      0.00      0.00        52
           3       0.00      0.00      0.00        61
           4       0.00      0.00      0.00        59
           5       0.00      0.00      0.00        56
           6       0.09      1.00      0.17        50
           7       0.00      0.00      0.00        56
           8       0.00      0.00      0.00        53
           9       0.00      0.00      0.00        52

    accuracy                           0.09       540
   macro avg       

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
for gamma in gammas:
  poly_svc = SVC(kernel='poly', gamma = gamma, C=C)
  poly_svc.fit(X_train, y_train)
  pred=poly_svc.predict(X_test)
  
  print(confusion_matrix(y_test,pred))
  print(classification_report(y_test, pred))
  print("with gamma", gamma)
  print("----------------------------------")

[[49  0  0  0  1  0  0  0  0  0]
 [ 0 51  0  0  0  0  0  0  0  0]
 [ 0  0 52  0  0  0  0  0  0  0]
 [ 0  0  0 61  0  0  0  0  0  0]
 [ 0  0  0  0 59  0  0  0  0  0]
 [ 0  0  0  0  0 55  0  0  0  1]
 [ 0  0  0  0  0  0 49  0  1  0]
 [ 0  0  0  0  0  0  0 56  0  0]
 [ 0  1  0  0  0  0  0  0 52  0]
 [ 0  0  0  0  0  0  0  0  0 52]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99        50
           1       0.98      1.00      0.99        51
           2       1.00      1.00      1.00        52
           3       1.00      1.00      1.00        61
           4       0.98      1.00      0.99        59
           5       1.00      0.98      0.99        56
           6       1.00      0.98      0.99        50
           7       1.00      1.00      1.00        56
           8       0.98      0.98      0.98        53
           9       0.98      1.00      0.99        52

    accuracy                           0.99       540
   macro avg       

In [ ]:
for gamma in gammas:
  sigmoid_svc = SVC(kernel='sigmoid', gamma = gamma, C=10)
  sigmoid_svc.fit(X_train, y_train)
  pred=sigmoid_svc.predict(X_test)
  
  print(confusion_matrix(y_test,pred))
  print(classification_report(y_test, pred))
  print("with gamma", gamma)
  print("----------------------------------")

[[ 0  0  0  0  0  0 50  0  0  0]
 [ 0  0  0  0  0  0 51  0  0  0]
 [ 0  0  0  0  0  0 52  0  0  0]
 [ 0  0  0  0  0  0 61  0  0  0]
 [ 0  0  0  0  0  0 59  0  0  0]
 [ 0  0  0  0  0  0 56  0  0  0]
 [ 0  0  0  0  0  0 50  0  0  0]
 [ 0  0  0  0  0  0 56  0  0  0]
 [ 0  0  0  0  0  0 53  0  0  0]
 [ 0  0  0  0  0  0 52  0  0  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        50
           1       0.00      0.00      0.00        51
           2       0.00      0.00      0.00        52
           3       0.00      0.00      0.00        61
           4       0.00      0.00      0.00        59
           5       0.00      0.00      0.00        56
           6       0.09      1.00      0.17        50
           7       0.00      0.00      0.00        56
           8       0.00      0.00      0.00        53
           9       0.00      0.00      0.00        52

    accuracy                           0.09       540
   macro avg       

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[ 0  0  0  0  0  0 50  0  0  0]
 [ 0  0  0  0  0  0 51  0  0  0]
 [ 0  0  0  0  0  0 52  0  0  0]
 [ 0  0  0  0  0  0 61  0  0  0]
 [ 0  0  0  0  0  0 59  0  0  0]
 [ 0  0  0  0  0  0 56  0  0  0]
 [ 0  0  0  0  0  0 50  0  0  0]
 [ 0  0  0  0  0  0 56  0  0  0]
 [ 0  0  0  0  0  0 53  0  0  0]
 [ 0  0  0  0  0  0 52  0  0  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        50
           1       0.00      0.00      0.00        51
           2       0.00      0.00      0.00        52
           3       0.00      0.00      0.00        61
           4       0.00      0.00      0.00        59
           5       0.00      0.00      0.00        56
           6       0.09      1.00      0.17        50
           7       0.00      0.00      0.00        56
           8       0.00      0.00      0.00        53
           9       0.00      0.00      0.00        52

    accuracy                           0.09       540
   macro avg       

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[ 0  0  0  0  0  0 50  0  0  0]
 [ 0  0  0  0  0  0 51  0  0  0]
 [ 0  0  0  0  0  0 52  0  0  0]
 [ 0  0  0  0  0  0 61  0  0  0]
 [ 0  0  0  0  0  0 59  0  0  0]
 [ 0  0  0  0  0  0 56  0  0  0]
 [ 0  0  0  0  0  0 50  0  0  0]
 [ 0  0  0  0  0  0 56  0  0  0]
 [ 0  0  0  0  0  0 53  0  0  0]
 [ 0  0  0  0  0  0 52  0  0  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        50
           1       0.00      0.00      0.00        51
           2       0.00      0.00      0.00        52
           3       0.00      0.00      0.00        61
           4       0.00      0.00      0.00        59
           5       0.00      0.00      0.00        56
           6       0.09      1.00      0.17        50
           7       0.00      0.00      0.00        56
           8       0.00      0.00      0.00        53
           9       0.00      0.00      0.00        52

    accuracy                           0.09       540
   macro avg       

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[ 0  0  0  0  0  0 50  0  0  0]
 [ 0  0  0  0  0  0 51  0  0  0]
 [ 0  0  0  0  0  0 52  0  0  0]
 [ 0  0  0  0  0  0 61  0  0  0]
 [ 0  0  0  0  0  0 59  0  0  0]
 [ 0  0  0  0  0  0 56  0  0  0]
 [ 0  0  0  0  0  0 50  0  0  0]
 [ 0  0  0  0  0  0 56  0  0  0]
 [ 0  0  0  0  0  0 53  0  0  0]
 [ 0  0  0  0  0  0 52  0  0  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        50
           1       0.00      0.00      0.00        51
           2       0.00      0.00      0.00        52
           3       0.00      0.00      0.00        61
           4       0.00      0.00      0.00        59
           5       0.00      0.00      0.00        56
           6       0.09      1.00      0.17        50
           7       0.00      0.00      0.00        56
           8       0.00      0.00      0.00        53
           9       0.00      0.00      0.00        52

    accuracy                           0.09       540
   macro avg       

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
