<a href="https://colab.research.google.com/github/merttezcan/ML-Homeworks/blob/main/svm_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.svm import SVC


iris = datasets.load_iris()
from sklearn.model_selection import train_test_split
X = iris.data
y = iris.target
X_train,X_test, y_train, y_test=train_test_split(X,y,test_size=0.30)
C = 1

gammas = [0.1, 1, 10, 100]

In [ ]:
linear_svc = SVC(kernel='linear', C=C)
linear_svc.fit(X_train, y_train)

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
pred=linear_svc.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,pred))
print(classification_report(y_test, pred))

[[16  0  0]
 [ 0 12  0]
 [ 0  2 15]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.86      1.00      0.92        12
           2       1.00      0.88      0.94        17

    accuracy                           0.96        45
   macro avg       0.95      0.96      0.95        45
weighted avg       0.96      0.96      0.96        45



In [ ]:
for gamma in gammas:
  rbf_svc = SVC(kernel='rbf', gamma = gamma, C=C)
  rbf_svc.fit(X_train, y_train)
  pred=rbf_svc.predict(X_test)
  
  print(confusion_matrix(y_test,pred))
  print(classification_report(y_test, pred))
  print("with gamma", gamma)
  print("----------------------------------")

[[16  0  0]
 [ 0 12  0]
 [ 0  4 13]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.75      1.00      0.86        12
           2       1.00      0.76      0.87        17

    accuracy                           0.91        45
   macro avg       0.92      0.92      0.91        45
weighted avg       0.93      0.91      0.91        45

with gamma 0.1
----------------------------------
[[16  0  0]
 [ 0 12  0]
 [ 0  3 14]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.80      1.00      0.89        12
           2       1.00      0.82      0.90        17

    accuracy                           0.93        45
   macro avg       0.93      0.94      0.93        45
weighted avg       0.95      0.93      0.93        45

with gamma 1
----------------------------------
[[14  0  2]
 [ 0 11  1]
 [ 0  1 16]]
              precision    re

In [ ]:
for gamma in gammas:
  poly_svc = SVC(kernel='poly', gamma = gamma, C=C)
  poly_svc.fit(X_train, y_train)
  pred=poly_svc.predict(X_test)
  
  print(confusion_matrix(y_test,pred))
  print(classification_report(y_test, pred))
  print("with gamma", gamma)
  print("----------------------------------")

[[16  0  0]
 [ 0 12  0]
 [ 0  3 14]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.80      1.00      0.89        12
           2       1.00      0.82      0.90        17

    accuracy                           0.93        45
   macro avg       0.93      0.94      0.93        45
weighted avg       0.95      0.93      0.93        45

with gamma 0.1
----------------------------------
[[16  0  0]
 [ 0 11  1]
 [ 0  2 15]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.85      0.92      0.88        12
           2       0.94      0.88      0.91        17

    accuracy                           0.93        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.94      0.93      0.93        45

with gamma 1
----------------------------------
[[16  0  0]
 [ 0 11  1]
 [ 0  2 15]]
              precision    re

In [ ]:
for gamma in gammas:
  sigmoid_svc = SVC(kernel='sigmoid', gamma = gamma, C=10)
  sigmoid_svc.fit(X_train, y_train)
  pred=sigmoid_svc.predict(X_test)
  
  print(confusion_matrix(y_test,pred))
  print(classification_report(y_test, pred))
  print("with gamma", gamma)
  print("----------------------------------")

[[ 0 16  0]
 [ 0 12  0]
 [ 0 17  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        16
           1       0.27      1.00      0.42        12
           2       0.00      0.00      0.00        17

    accuracy                           0.27        45
   macro avg       0.09      0.33      0.14        45
weighted avg       0.07      0.27      0.11        45

with gamma 0.1
----------------------------------
[[ 0 16  0]
 [ 0 12  0]
 [ 0 17  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        16
           1       0.27      1.00      0.42        12
           2       0.00      0.00      0.00        17

    accuracy                           0.27        45
   macro avg       0.09      0.33      0.14        45
weighted avg       0.07      0.27      0.11        45

with gamma 1
----------------------------------
[[ 0 16  0]
 [ 0 12  0]
 [ 0 17  0]]
              precision    re

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classificat